### ISSUE TITLE
Suitable types - Mini Summit Deep Dive next steps

### ISSUE THREAD

**Issue by mhdawson** [nodejs/next-10#104]
- [ ] Document target flow for Node.js type generation
- [x] Staring discussion on adopting Electron style guide
- [x] Further explore Electron TypesParser to see if it can be used to generate JSON 
  for Node.js project
- [ ] Explore how we'd move metadata from comments/YAML to markdown as they
  are currenlty not rendered and it would also help exposing through TypesParser
- [ ] Rethink how doc is structured with respect to API documentation versus other 
  things. Should JavaScript API docs and other topics be more separated?

**Comment by mhdawson** [comment]
Node.js discussion related to Electron Style guide - nodejs/node#40953

**Comment by mhdawson** [comment]
PR for the first entry in the list -https://github.com/nodejs/node/pull/41464

**Comment by sheplu** [comment]
Should this issue be linked (or integrated) into the new documentation model ? 

Seems like the first point landed, and the other are related to the documentation - if I am not mistaken.

**Comment by mhdawson** [comment]
Current assumption is the documentation from @ovflowd  proposal will cover this.
