### ISSUE TITLE
Next 10 - Summit OpenJS World 2022

### ISSUE THREAD

**Issue by sheplu** [nodejs/next-10#112]
Agenda for meeting on June 16th at OpenJS World collaborator summit + remote over Zoom.

And for easier access the current times:

[Overall schedule](https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit#gid=0)
13:00 Central/18:00 GMT - ESM (80 mins)
14:20 Central/19:20 GMT - Break (10 mins)
14:30 Central/19:30 GMT - Observability (80 mins)
15:50 Central/20:50 GMT - Wrap up (10 mins)

For each topic the planned flow is generally

Is the current state good enough to ensure future success or are there things the project should be doing to improve them?
If the answer to 1) is that significant improvements are needed, document specific things that we work on/prioritize

For those who will be participating remote here is the zoom info:

981 2298 5707 https://zoom.us/j/98122985707

There is a passcode required which I'll add to this issue near the time the session starts

--------------------------------------

This year June 6th to June 10 will be held an OpenJS World in Austin, Texas.

It is already planned to have two days to plan the Collaborator Summit:
- Thursday June 9th
- Friday June 10th

It would be really nice to have a meeting to discuss and review:
- what we did
- what are the next targets
- how we can improve / change

What are the steps we need to take to have a slot there ?
- which day
- how long
- precise topic
- plan to record / stream it ?

This is just a first gorup of ideas, i will edit it later / add feedback :)

**Comment by mhdawson** [comment]
Discussion from the Next-10 meeting today 

  * Common session (all collaborators) intro to Next-10 call to get involved 
  * Review modern HTTP plan/progress
  * Baseline review (start with review of what we have, then whiteboard session to brainstorm
    additions/removals)
    * https://github.com/nodejs/node/blob/master/doc/contributing/technical-priorities.md
    * https://github.com/nodejs/node/blob/master/doc/contributing/technical-values.md
    * https://github.com/nodejs/next-10/blob/main/CONSTITUENCIES.md
    * https://github.com/nodejs/next-10/blob/main/CONSTITUENCY-NEEDS.md
  * Technical deep dives
    * ESM 
    * Observability

**Comment by mcollina** [comment]
I'll be there.

**Comment by mhdawson** [comment]
Michael and Joe volunteered to do the submissions, will try to do that in next week or so and share in this issue.

**Comment by mhdawson** [comment]
Would it make sense for @mcollina or @ronag to submit the collab summit session for - Review modern HTTP plan/progress?

**Comment by mhdawson** [comment]
Submitted these two:
* https://github.com/openjs-foundation/summit/issues/316
* https://github.com/openjs-foundation/summit/issues/315

**Comment by mcollina** [comment]
Here is mine on http: https://github.com/openjs-foundation/summit/issues/317

**Comment by mhdawson** [comment]
@mcollina thanks!

**Comment by mhdawson** [comment]
Looking at the deep dives planned for the collaborator summit.

ESM
Observability

I'm wondering if there are additional/specific people we should invite (possibly virtual).

The current schedule shows the sessions at 1:00 to 4:00 Central (GMT-5) on Thursday June 9.

@nodejs/diagnostics do you have suggestions of who we might want to make sure is aware of the Observability session ?

@nodejs/modules do you have suggestion of who we might want to make sure is aware of the ESM session?

**Comment by sheplu** [comment]
in both cases should we see if we have people from vendors which would be interested ? I am thinking of new relic on the observability part, and maybe some librairies authors + APM vendors (but i do think they already have some people in the tagged groups)

**Comment by legendecas** [comment]
As a maintainer of OpenTelemetry, I'm interested in the observability part.

**Comment by Qard** [comment]
I'll be there. :)

**Comment by mhdawson** [comment]
@legendecas great to hear you will be there. It will be great to hear from you in terms of requirements/needs etc on the part of OpenTelemetry.

**Comment by JakobJingleheimer** [comment]
I could do, but I wouldn't supply anything of quality in the middle of the night (I presume the same for Maël). Perhaps Bradley, Geoffrey, or Guy?

**Comment by mhdawson** [comment]
For those who will be participating remote here is the zoom info:

981 2298 5707	https://zoom.us/j/98122985707

There is a passcode required which I'll add to this issue near the time the session starts

**Comment by mhdawson** [comment]
@bmeck, @guybedford, @GeoffreyBooth, FYI.

**Comment by GeoffreyBooth** [comment]
Hi, I’ll be there. @JakobJingleheimer would you be able to call in if it were moved into the morning Austin time?

**Comment by mhdawson** [comment]
And for easier access the current times:

[Overall schedule](https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit#gid=0)
13:00 Central/18:00 GMT - ESM (80 mins)
14:20 Central/19:20 GMT - Break (10 mins)
14:30 Central/19:30 GMT - Observability (80 mins) 
15:50 Central/20:50 GMT - Wrap up (10 mins)

For each topic the planned flow is generally

1) Is the current state good enough to ensure future success or are there things the project should be doing to improve them?
2) If the answer to 1) is that significant improvements are needed, document specific things that we work on/prioritize

**Comment by JakobJingleheimer** [comment]
Yeah! I could attend morning Austin time! Which day would this be?

**Comment by mhdawson** [comment]
zoom link with password embedded - https://zoom.us/j/98122985707?pwd=cEdBa3BtN0hMa1ZJRmEzRWpON01VZz09

**Comment by mhdawson** [comment]
PR for minutes, please review and help if there are omissions, additional key points etc. - https://github.com/nodejs/next-10/blob/7e644201503d80429ce504aae5ab49da38f13460/meetings/summit-jun-2022.md
