### ISSUE TITLE
Next-10 Mini summit  - WASM and Permissions/policies/security model

### ISSUE THREAD

**Issue by mhdawson** [nodejs/next-10#124]
# Next-10 Mini summit  - WASM and Permissions/policies/security model

## When

Thursday April 7th
10-2 Eastern

In your time: https://www.timeanddate.com/worldclock/fixedtime.html?msg=Next-10+Mini+summit+-+WASM+and+Permissions%2Fpolicies%2Fsecurity+model&iso=20220407T10&p1=188&ah=4

## Where
zoom: https://zoom.us/j/99950131676

## Agenda
    * WASM - 90 mins
    * Break 15 mins
    * Permissions/policies/security model - 90 mins
    * Break 15 mins
    * Wrap up and capture next actions
    
## Misc

Will look to promote through 
- [x] TSC agenda
- [x] post a collaborators discussion - https://github.com/nodejs/node/discussions/42448

**Comment by mhdawson** [comment]
@bmeck do you have any suggestions on who we should reach out to with an invite for the section on Permissions/policies/security model.

**Comment by mhdawson** [comment]
@cjihrig, @linclark. Do you have any suggestions of who we might reach out to invite for the discussion on WASM. For context - we've identified it as a [key technical priority](https://github.com/nodejs/node/blob/master/doc/contributing/technical-priorities.md#webassembly) to the success of Node.js going forward and this discussion is to identify what the key things we should be working on in that context.

**Comment by cjihrig** [comment]
On the Node.js side, I'd recommend @devsnek, @guybedford, and @tniessen.

**Comment by mhdawson** [comment]
@cjihrig thanks!

**Comment by linclark** [comment]
I'd be happy to join, and @lukewagner should definitely be involved. He's driving a lot of key proposals in this space. He just confirmed that he's available at this time and happy to join.

**Comment by mhdawson** [comment]
@linclark, thanks looking forward to seeing you there.

**Comment by devsnek** [comment]
I haven't been as active in the last couple months but I'd be happy to drop by.

**Comment by targos** [comment]
Could the event be added to the Foundation's calendar?

**Comment by joesepi** [comment]
> Could the event be added to the Foundation's calendar?

Added! @targos @mhdawson

**Comment by mhdawson** [comment]
@joesepi thanks for doing that, I missed that when creating.

**Comment by mhdawson** [comment]
@bmeck another ping to see if you have any suggestions on who might be good invitees for the security model/policies section.

**Comment by sheplu** [comment]
could this be of interest for the N-API WG or addon API WG ?

**Comment by mhdawson** [comment]
@sheplu good point, sent an email to the node-api team members as an FYI.

**Comment by mhdawson** [comment]
@nodejs/security-triage FYI, thinking people doing the triage might be interested in the discussion on the security model.

**Comment by lirantal** [comment]
I'd love to join but I'm on a day off to spend time with family on the 7th so would have to watch the recording.
I think it's worth pinging @fraxken @DanielRuf and @UlisesGascon who might find this interesting and would want to join.

**Comment by fraxken** [comment]
Thanks for pinging me. Yes I am clearly interested, I will participate.

**Comment by UlisesGascon** [comment]
I will love to participate! Thanks @lirantal!

**Comment by vdeturckheim** [comment]
Sorry for coming late, I will join

**Comment by mhdawson** [comment]
Doc for minutes - https://docs.google.com/document/d/18xnPq-hALW0Np_2VuG3tsQl8qufawCLIF5CB7eFvmo8/edit

**Comment by tniessen** [comment]
Will be there for the first part!

**Comment by jasnell** [comment]
I want to be there but have a conflict today. Looking forward to see what comes out of the agenda tho

**Comment by mhdawson** [comment]
PR for minutes - https://github.com/nodejs/next-10/pull/127
