### ISSUE TITLE
Revisit time slots

### ISSUE THREAD

**Issue by mmarchini** [nodejs/next-10#13]
The currently proposed meeting time slots were borrowed from TSC meetings, where we optimized for attendance of TSC members. Since in general the next-10 meetings are composed by many other folks, I suggest we revisit the time slots in an attempt to increase participation. It might also be easier to reduce to one or two time slots (instead of four), as well as consider other days instead of Wed/Thu.

**Comment by mmarchini** [comment]
Ok, I created a big doodle with all time slots that don't conflict with any Node.js meetings as well as some OpenJSF meetings: https://doodle.com/poll/wmwv8uh8b4tzyzt7#calendar. @nodejs/next-10 please fill the doodle with time slots available for you.

**Comment by mmarchini** [comment]
@nodejs/next-10 remember to choose a time that works for you on the doodle, so we can determine a meeting time moving forward.

**Comment by mhdawson** [comment]
@mmarchini just wondering if you have the output from the doodle in terms of what other times we might consider?

**Comment by mhdawson** [comment]
Meeting moved, closing
