### ISSUE TITLE
PSA: #nodejs-next-10 channel in the OpenJS Foundation slack

### ISSUE THREAD

**Issue by mmarchini** [nodejs/next-10#14]
I created a [channel](https://openjs-foundation.slack.com/archives/C0197V5VDC2) in the [OpenJS Foundation Slack](https://slack-invite.openjsf.org/). It can help with real-time communication as well as reminders of the meeting.

**Comment by designMoreWeb** [comment]
Awesome

**Comment by mhdawson** [comment]
@mmarchini can we close this now, although maybe it should be PR'd into the README.md for the repo.

**Comment by mmarchini** [comment]
https://github.com/nodejs/next-10/pull/21
