### ISSUE TITLE
Types/TypeScript - Follow on mini-summit - July 28 at 10:30 ET

### ISSUE THREAD

**Issue by mhdawson** [nodejs/next-10#149]
Time: 28 July at 10:30 - 12 ET
Link: https://zoom.us/j/99950131676

In terms of the time we've co-ordinated with @BethGriggs to have the Release WG meeting cut short to 30 minutes so that we can start at that time.

If you convert to your timezone, feel free to paste the mapping into a comment so that others may not need to do that.

There has been a lot of follow on discussion on Types/TypeScript support and what the Node.js project since both the
first [mini-summit](https://github.com/nodejs/next-10/blob/main/meetings/summit-nov-2021.md) and a related session in the collaborator summit in June.

Most recently there has been active discussion in - [43818](https://github.com/nodejs/node/issues/43818). 

To come up to speed reviewing those prior discussions would be useful.

The goal should be to discuss/agree enough so that we can update: https://github.com/nodejs/node/blob/main/doc/contributing/maintaining-types-for-nodejs.md to add additional/goals agreed approaches in order to enable work going forward.

**Comment by mhdawson** [comment]
FYI: 

@nodejs/loaders 
@mcollina 
@JakobJingleheimer
@kdy1
@Qard 
@giltayer  
@meyfa 
@ethan-arrowood
@aduh95 


I think I've added everybody who said they were interested, if I've missed anybody please add them. Same goes for if there is anybody else we think we should invite.

**Comment by ljharb** [comment]
cc @nodejs/typescript

**Comment by mhdawson** [comment]
@ljharb good point about that at mention :)

**Comment by styfle** [comment]
> Time: 28 June at 10:30 ET

Should this say July instead of June?

**Comment by kdy1** [comment]
@mhdawson I want to invite @kwonoj

**Comment by mhdawson** [comment]
@styfle thanks, fixing month.

**Comment by mhdawson** [comment]
Nevermind, seeing it  was already fixed.

**Comment by mhdawson** [comment]
@dky1 thanks, they just need to join with the link in the description.

**Comment by romulocintra** [comment]
+ me :) please

**Comment by F3n67u** [comment]
I am also interested in this topic. Because my English speaking is not good, so I wanna attend this meeting as a silent spectator. @F3n67u

**Comment by mhdawson** [comment]
@F3n67u yes.  Everybody is welcome either to listen or to participate at the level they are comfortable.   At the scheduled time just join the link above and you can stay muted or talk if you'd like.

**Comment by mhdawson** [comment]
Minutes doc for the meeting - https://docs.google.com/document/d/1zrtpppIcuclwNDglK-02iSq_5Kw7Z5Yq3rwc5nbBt0E/edit

**Comment by ErickWendel** [comment]
I won't be able to attend this one but I find it interesting. Will it be recorded and available on Youtube later?

**Comment by kdy1** [comment]
I may not be able to attend it (not sure at the moment)

**Comment by mhdawson** [comment]
PR for minutes - https://github.com/nodejs/next-10/pull/150
