### ISSUE TITLE
Plan for collaborator session in Dublin

### ISSUE THREAD

**Issue by mhdawson** [nodejs/next-10#159]

**Comment by mhdawson** [comment]
What would use for an easy retro type type tool?

**Comment by bnb** [comment]
https://easyretro.io/

**Comment by mhdawson** [comment]
# Agenda

* Technical prioriites brainstorm - 
  * Board for thjis year - https://easyretro.io/publicboard/J7hq238p2gSasf0xP3zuGfGU4Jr2/7133f400-4af1-4133-8f5f-7b4f5adf2283
  * Last year results - https://easyretro.io/publicboard/cLBIBu3wA2Um7qIziXq1zmC4gdi1/1db5ea23-fee3-4da0-bb7b-a5ea49d810e7?sort=votes

* Community brainstorm 
  * Board for brainstorm - https://easyretro.io/publicboard/J7hq238p2gSasf0xP3zuGfGU4Jr2/6dfc326f-a253-4268-b320-6cda3f4e300c
  * Last year results - https://user-images.githubusercontent.com/4048656/106966137-95bccb80-66f9-11eb-860c-cd6fe7d82790.png

* Enabling the project
  * Communication/sharing of priorities with collaborators
  * Helping people feeling empowed to pick up/run with priorities

* Review of technical priorities against the existing list - https://github.com/nodejs/node/blob/main/doc/contributing/technical-priorities.md

* Have constituencies/needs changed ?
  * https://github.com/nodejs/next-10/blob/main/CONSTITUENCIES.md
  * https://github.com/nodejs/next-10/blob/main/CONSTITUENCY-NEEDS.md

* Next Steps

**Comment by mhdawson** [comment]
@nodejs/members

We discussed in the next-10 meeting today and as part of the collaborator summit we'd like to brainstorm technical priorities and what's going well/not so well in the project. There are 2 easy retro board, it would be great to have you all add your thoughts by adding entries to the easy retro boards.

The two easy retro boards for those are:

* Technical Priorities - https://easyretro.io/publicboard/J7hq238p2gSasf0xP3zuGfGU4Jr2/7133f400-4af1-4133-8f5f-7b4f5adf2283
* Community - https://easyretro.io/publicboard/J7hq238p2gSasf0xP3zuGfGU4Jr2/6dfc326f-a253-4268-b320-6cda3f4e300c

This comment has lists for past boards if you need some additional context - https://github.com/nodejs/next-10/issues/159#issuecomment-1253797074

**Comment by mhdawson** [comment]
Top priorities brainstorm board

![image](https://user-images.githubusercontent.com/9373002/195361444-23b95d35-1297-4b29-bb5c-d5199d80ff91.png)
![image](https://user-images.githubusercontent.com/9373002/195361583-c1d3fe87-4f11-4c00-9f5d-92cc42a98007.png)

**Comment by mhdawson** [comment]
Community Brainstorm

![image](https://user-images.githubusercontent.com/9373002/195362284-276aa5d3-da99-4400-bbca-f3c65a75a3fe.png)

**Comment by sheplu** [comment]
also the result from the second board

![Screenshot 2022-10-12 at 15-54-42 EasyRetro Improve your team with fun sprint retrospectives](https://user-images.githubusercontent.com/1133916/195362693-e5290801-705e-4275-9ccc-7d7ea1d0a843.png)

**Comment by sheplu** [comment]
## Technology Trend 2021

TypeScript / Type
Serverless
Web Assembly
Tracing
Single Binary
CI/CD/Automation
Permission/Policies
Graphql/grpc
Prometheus style metrics
Secure Software bill of materials
Pre compilation
Cryptocurrency
IoT
Zero knowledge
Object capability (OCAP)
Ecosystem Comparability and maintenance



## Technology Trend 2022

ESM support (new) 
TypeScript / Types (-1)
Serverless (-1)
Small footprint runtime (new)
Observability (-5)
DX (new)
WinterCG (new / ecosystem?)
Http3 (new)
WASM (-6)
Supply chain security (+6)
eBPF (new)

## Technology take 2021-2022

Types / TS need to be a core subject (linked to the new tc39 type proposal - also PR and discussion about linking TS)
Serverless still a key priority (WinterCG group ?)
Security still on the list, how to improve what should we change ? (ecocystem wide maybe)

Some stuff are in progress
- binary
- diagnostic (tracing, prometheus metrics?)

## Node.js features 2021

Modern HTTP (undici)
documentation
ESM
ES version support
diagnostic
Quic
Worker thread support
fs hook
argument parser
Native bundling support (TS)
FIPs support
N-API
better installer / binary management
AoT (v8)
OpenSSL support
Iteration on policies / sandbox primitive
Alternative SSL support

## Node.js features 2022

Docs (+1)
Stable fetch (new / http support ?)
undici (-2)
ESM import mocking (-1)
hot reload (new)
esm/cjs interop (-2)
tests(pretty + more) (new)
python -m simple http server (new)
embeded nodejs (new)
better perf(stream) (new)
expand diagnostic_channel (-6)


## Features take 2021-2022
Documentation is a key point to adress (next-10 initiative on the way)
ESM seems crucial also (function, doc, recommandation, interop...)
Diagnostic seems to be a key concept to improve 

Some functionnalityes landed:
- Fetch
- undici
- argument parser
- openssl



## Other 2021

vulnerabily management and reporting
compatibility with other env

## Other 2022

Improving CI reliability (new)
CITGM maintenance (new)
Fuzzing (new)
performance (bun, deno) (new)
Vulnerability management (-4)

## Other take 2021-2022

Vulnerability and security are key
global maintenance (on multiples topics)

**Comment by sheplu** [comment]
## Key focus areas 2021

collaborator
attracting collaborator
concensus process
more communication
large changes
mentorship is great
leadership model
buuild technology

## Key focus areas 2022

being well welcomed
education
sustainable outreach
funnel contributor onboarding/communication
increase corporate contribution
enabling larger initiatives
further built in tooling
faster startup time

## Key take 2021-2022

Good collaboration coming but hard to retain
Need to reach for companies for support / money / contribution
Need to work on better follow up with new contributor
How to have bigger initiatives

## Obstacles 2021

Consensus model
different agenda
how to contribute
timezone
to few knowledgeable people (stream, ...)
PR staled
Size of project
jenking log are hard
long build time

## Obstacles 2022

flaky CI / test
communication with community
lack of good first issue
primordials
ESM / CJS interop for module author
money
corporate priorities
nice/area don t gave reviewer
OpenJS foundation limitation
Timezone
how to prioritize
burnout
not enought contribution from ecosystem
work more asynchronously

## Obstacle 2021-2022

Area without enough contributors (project size, burnout, ...)
timezone is still an issue
tests/build is long and log can be hard
money/corporate was a big talk


## working well 2021

Active working groups
release cadence
codeowner
automation

## working well 2022

PR process
Collab summit
OpenSSF
New collaborator
Automation on github
stable ecosystem (less complaits)
onboarding collaborator

## Working well take 2021-2022

Working group onboarding collaborator and people joining seems fine
automation played a key role on helping members
PR speed seems to be better
