### ISSUE TITLE
Next 10 years for collaborators

### ISSUE THREAD

**Issue by mmarchini** [nodejs/next-10#16]
So far most of the discussion has been user-focused, which is great as it helps us set user-centric goals for the project. In the future we also need to discuss what the next 10 years should look like for collaborators, discussing and re-evaluating our current contribution workflow, consensus seeking model, leadership model, etc. We might come out of the discussion agreeing that everything is fine as is, or we might come up with ideas for improvements. Either way, I think it's an important topic to discuss.

**Comment by Qard** [comment]
My only suggestion is: automate all the things! 🤓

**Comment by joesepi** [comment]
Easy Retro board for meeting currently happening (now): 
https://easyretro.io/publicboard/8284sHrgEOQQG7KZMlDeSoYfTq73/bbf510ad-bc9c-41f7-ab8c-ea19a1fc8377

**Comment by mmarchini** [comment]
results

![img-2021-02-04-145920](https://user-images.githubusercontent.com/4048656/106966137-95bccb80-66f9-11eb-860c-cd6fe7d82790.png)

**Comment by mhdawson** [comment]
Closing as covered in mini-summit and we will open follow on issues as outlined in: https://github.com/nodejs/next-10/pull/82
