### ISSUE TITLE
Review easy retros from Collab summit and do updates as appropriate

### ISSUE THREAD

**Issue by mhdawson** [nodejs/next-10#165]

**Comment by mhdawson** [comment]
@sheplu landed these two
- https://github.com/nodejs/next-10/pull/176
- https://github.com/nodejs/next-10/pull/174

**Comment by mhdawson** [comment]
@sheplu, will open PR to update technical priorities https://github.com/nodejs/node/blob/main/doc/contributing/technical-priorities.md as the last step

**Comment by sheplu** [comment]
https://github.com/nodejs/node/pull/47523

**Comment by sheplu** [comment]
tagged all people that commented, I don't know if this need to be review by specific people / tsc

**Comment by mhdawson** [comment]
Agreed can be closed in Next-10 meeting today.
