### ISSUE TITLE
Get collab summit attendee list for follow on disussion on priorities

### ISSUE THREAD

**Issue by mhdawson** [nodejs/next-10#167]

**Comment by sheplu** [comment]
Using the albums from Tony: https://www.flickr.com/photos/154890703@N06/albums/72177720302771381/with/52418468443/ (and mostly this one)

- Claudio
- Michael
- Matteo
- Ruy
- Danielle
- Jean
- Someone I dont know the name
- Stephen
- Beth
- Ethan
- James
- James' son (sorry don't have the name)
- Liran
- Santiago
- Someone I dont know the name
- Someone I dont know the name
- Someone I dont know the name
- Anton ?

Missing from the picture
- Michael
- Waleed
- Maybe others ?

This is the list of people during the collaborator summit, maybe not all were present during the next-10

**Comment by mhdawson** [comment]
List looks good. Closing as done.
