### ISSUE TITLE
Remove Inactive members - Jan 17

### ISSUE THREAD

**Issue by mhdawson** [nodejs/next-10#183]
The new year is a good time to trim down the list of members to those who are active.

Those who I have seen in meetings or having commented in issues in the  last 3 months 
[@BethGriggs](https://github.com/BethGriggs) - Bethany Nicolle Griggs
[@bmeck](https://github.com/bmeck) - Bradley Farias
[@bnb](https://github.com/bnb) - Tierney Cyren
[@darcyclarke](https://github.com/darcyclarke) - Darcy Clarke
[@dominykas](https://github.com/dominykas) - Dominykas Blyžė
[@joesepi](https://github.com/joesepi) - Joe Sepi
[@legendecas](https://github.com/legendecas) - legendecas
[@ljharb](https://github.com/ljharb) - Jordan Harband
[@mhdawson](https://github.com/mhdawson) - Michael Dawson
[@ovflowd](https://github.com/ovflowd) - Claudio Wunder
[@Qard](https://github.com/Qard) - Stephen Belanger
[@ruyadorno](https://github.com/ruyadorno) - Ruy Adorno
[@sheplu](https://github.com/sheplu) - Jean Burellier

Anybody else who does not responde indicating they plan to be active I'll move to emeritus on Jan 
16th.  It's easy to move people back so just let me know if I move somebody to emeritus who should not have been.

@nodejs/next-10

**Comment by sheplu** [comment]
I think @ruyadorno was in some meetings lately ?

**Comment by mhdawson** [comment]
@sheplu thanks, adding to the list above

**Comment by mhdawson** [comment]
PR to remove inactive members https://github.com/nodejs/next-10/pull/189

**Comment by mhdawson** [comment]
Done
