### ISSUE TITLE
Session proposals for the next Collaborator Summit - what should we submit

### ISSUE THREAD

**Issue by mhdawson** [nodejs/next-10#194]
Some of the ideas we talked about in the last meeting:
  * Serverless/Functions Deep dive?
  * Observability/Diagnostic channel (sync with Diagnostics team on this one)
  * Building long term collaborators 

Lets keep adding ideas to this issue and discuss again next time we get together.

**Comment by mhdawson** [comment]
Translation - what makes sense to translate or not and documenting the project's approach.

**Comment by mhdawson** [comment]
Discussion was we can assume 1 hour, possibly 2 if we have 2 good sessions.

**Comment by sheplu** [comment]
Corporate support - How to have funding (linked to [PR](https://github.com/nodejs/next-10/issues/177)

**Comment by mhdawson** [comment]
From discussion, one possible submission

Keeping the project healthy
- Building long term collaborators
- Encouraging companies/people to support the project
  - Reward your people for contributing to the project
  - Contribute to the Node.js infrastructure
  - Join the OpenJS Foundation
  - Sponsor collaborator summit
  - Contribute to our LFX account??
  - Sponsor collaborator summit
  -  ???

Second session (regular collaborator check)
- What's going well, not so well, etc.
- Technical priority review

**Comment by mhdawson** [comment]
2 proposals submitted:

- https://github.com/openjs-foundation/summit/issues/354
- https://github.com/openjs-foundation/summit/issues/351
