### ISSUE TITLE
Needs/want of constituencies

### ISSUE THREAD

**Issue by mhdawson** [nodejs/next-10#20]
As agreed in meeting this week next focus area should be:

Discussed that next focus area should be what does each constituencies need

    * This should actually include #16 as the Node.js maintainers are one of the constituencies
       listed.
    * Next meeting to brainstorm on what each constituency needs
    * Action -> Darcy to setup boards, for each constituency , with following headings:need, don’t
      need, want, don’t want

Created this issue so that it's on the agenda for next time.

**Comment by sheplu** [comment]
Link to the FunRetro so that anyone can update / add new elements if needed: 
https://funretro.io/publicboard/QnR9oTPWKKfMnff3RxvPiNCY3Om2/3c3f4803-9259-42b4-8ea9-2a2f43ab4c36

**Comment by mhdawson** [comment]
Fun retro we used

https://funretro.io/publicboard/QnR9oTPWKKfMnff3RxvPiNCY3Om2/3c3f4803-9259-42b4-8ea9-2a2f43ab4c36. We'll continue to work on this next time.

screecap of what it looked like at end of meeting: 
![constituent needs](https://user-images.githubusercontent.com/9373002/94868392-1b113600-0411-11eb-8fef-c95612932a65.png)

**Comment by mhdawson** [comment]
![image](https://user-images.githubusercontent.com/9373002/97453000-b4960f80-190b-11eb-8293-b1fd9b597742.png)

**Comment by mhdawson** [comment]
Added, list from discussions today.

**Comment by mhdawson** [comment]
Getting more input through https://github.com/nodejs/next-10/issues/48 - closing.
