### ISSUE TITLE
Next Deep Dive

### ISSUE THREAD

**Issue by sheplu** [nodejs/next-10#228]
Topics ?
- Serverless (again)
- Node-API / uvwasi
- other ?

**Comment by wesleytodd** [comment]
I wonder if talking about #177 would be good? I think the technical deep dives are great, but seems like there is a fair bit to talk about in regard to corporate sponsorship and supporting the project(s).

**Comment by sheplu** [comment]
I think this could be a good point, maybe not a public one but it would make sens to have it splitted in two part
- need from the community
- multiple path to corporate support

Maybe it would make sens to have some people from the foundation (+ LF and OSPO ? )

**Comment by joesepi** [comment]
I dont have time for a long thoughtful comment here, however, @wesleytodd and I were chatting earlier today and it sorta dawned on me that perhaps the biggest issue facing Node.js (thinking about "the next 10 years") may be the issue of not having great pathways for new contributors to get involved and grow within the project. I realize that I dont have stats at hand on growth/decline of contributions, but I worry that if a few key people left the project, we would have serious gap in leadership and knowledge.

**Comment by mhdawson** [comment]
We ageed today in the team meeting that the next deep dive should be: `Advocacy and promotion for the project`

We need to

1) Identify volunteer to chair/run the deep dive
2) Agree on the date


Initial suggestion for date was Fed 22nd 10-12 ET but that seems to conflict with some conferences. @sheplu what's the next Thursday after that which might work?

**Comment by sheplu** [comment]
I think we can try to do it on February 29th.
I can run/chair the deep dive :)

**Comment by mhdawson** [comment]
@sheplu sounds good to me.

**Comment by sheplu** [comment]
Created an issue linked to the deep dive https://github.com/nodejs/next-10/issues/247
We can discuss the time during our next call

**Comment by wesleytodd** [comment]
Closing this in favor of the deep dive agenda linked above.
