### ISSUE TITLE
Discuss initial cut at text for ambassador program

### ISSUE THREAD

**Issue by mhdawson** [nodejs/next-10#266]
https://github.com/mhdawson/io.js/blob/ambassador-program/doc/contributing/advocacy-ambasador-program.md

**Comment by mhdawson** [comment]
@nodejs/next-10 we discussed in the team meeting today, and made some edits.  Pl,an is for me to open the issue in the Node.js/node repo on Monday unless there are concerns/objections raised before then.

If you can take a look before then and let me know if you have any comments or suggestions that would be great.

**Comment by mcollina** [comment]
I would like to invite feedback from @anfibiacreativa and @whitep4nth3r, with whom I brainstormed a bit around the problem (and IMHO they would both make great ambassadors).

**Comment by whitep4nth3r** [comment]
> The project aims to support and encourage developer advocates

Do ambassadors need to be "developer advocates" specifically? What about developers building in public with Node?

>  that this content does not overly market their employer

I like this addition a lot. It may be worth also adding in something like "does not overly market their employer or product/business" if you choose to expand the pool of eligible ambassadors to not _only_ developer advocates.

It also might be useful to stipulate that for communication purposes and collaboration opportunities, ambassadors should be a member of the OpenJS Slack.

**Comment by mhdawson** [comment]
@whitep4nth3r 
> Do ambassadors need to be "developer advocates" specifically? What about developers building in public with Node?

Thanks for the suggestion update to say developers or developer advocates

**Comment by mhdawson** [comment]
PR  created here - https://github.com/nodejs/node/pull/52857

**Comment by anfibiacreativa** [comment]
@mhdawson I had written draft in a private repo to brainstorm with @mcollina and @whitep4nth3r  (keeping it there not to confuse anyone). I would like to share that with the rest. Should I post it here?

**Comment by mhdawson** [comment]
@anfibiacreativa is that draft an alternative to https://github.com/nodejs/node/pull/52857 ? I so then commenting in that issue might make sense at this point.

**Comment by mhdawson** [comment]
PR is opened so closing this one out.

**Comment by trivikr** [comment]
> PR is opened so closing this one out.

@mhdawson did you miss closing this issue?

**Comment by mhdawson** [comment]
Closing as PR landed in Node.js/node repo
