### ISSUE TITLE
Add zoom link to recurring calendar invite

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/next-10#307]
> [!NOTE]  
> This is cleanup from https://github.com/nodejs/admin/issues/923

People interacting with the WG via https://nodejs.org/calendar are met with not enough information to join.

![image](https://github.com/user-attachments/assets/10aa1e47-7dca-4f24-873c-d576c85232df)

And they won't necessarily know to look for issues like https://github.com/nodejs/next-10/issues/306

Further https://nodejs.org/en/about/get-involved/events only displays events with a zoom link.

To resolve all of this, please add https://zoom.us/j/99950131676 (which I think is a durable enough link, taken from the above issue) to the calendar.

**Comment by marco-ippolito** [comment]
Done can you check again?

**Comment by JakobJingleheimer** [comment]
This appears to be complete (I see it in the calendar event description).

**Comment by bmuenzenmeyer** [comment]
looking good! thanks!
