### ISSUE TITLE
Should we use TCQ for meetings?

### ISSUE THREAD

**Issue by mmarchini** [nodejs/next-10#33]
https://tcq.app/ is used on TC39 meetings to coordinate discussions, give everyone a fair chance to reply, and avoid people talking over each others. Since this WG has a lot more discussions than other WGs (where we go over issues), it might make sense to use TCQ on our meetings. Thoughts?

**Comment by mhdawson** [comment]
I've not used TCQ, maybe it would make sense to try it out by having you lead discussion on one of the upcoming topics and use it as part of that as a way of introducing to the team?

**Comment by mhdawson** [comment]
I think this is stale. I'm going to close it but please reopen if that was not the right thing to do.
