### ISSUE TITLE
Key Technical Areas - Brainstorm to generate list

### ISSUE THREAD

**Issue by mhdawson** [nodejs/next-10#39]
Brainstorm using funretro or equivalent as first step on identifying key technical areas/trends that are important in relation to the needs of the constituents.

**Comment by darcyclarke** [comment]
Link/reference to the funretro board we put together here: https://easyretro.io/publicboard/cLBIBu3wA2Um7qIziXq1zmC4gdi1/f2334393-fe0f-4202-8ee5-0ef677e0ff9e

![Screen Shot 2021-01-21 at 1 12 41 PM](https://user-images.githubusercontent.com/459713/105393475-629f1600-5bea-11eb-87f2-54df265d204e.png)

**Comment by mhdawson** [comment]
@darcyclarke just went to look at adding the picture,very happy to see it already there, thanks!

**Comment by mhdawson** [comment]
One of the next steps in addition to discussing in the next meeting: https://github.com/nodejs/next-10/issues/43

**Comment by darcyclarke** [comment]
Community Board - ready to be shared abroad (cloned from our original discussion):  https://easyretro.io/publicboard/cLBIBu3wA2Um7qIziXq1zmC4gdi1/1db5ea23-fee3-4da0-bb7b-a5ea49d810e7

**Comment by mhdawson** [comment]
Feedback from collaborators:


![image](https://user-images.githubusercontent.com/9373002/117192219-73e1ec00-adaf-11eb-9d1b-9133e10c31d3.png)

**Comment by mhdawson** [comment]
* closing as covered in mini-summit and we will open follow on issues as outlined in: https://github.com/nodejs/next-10/pull/82
