### ISSUE TITLE
Adding native fetch() to node.js

### ISSUE THREAD

**Issue by Mlocik97** [nodejs/next-10#50]
Hello,

it would be nice to add `fetch()` to node.js even when we don't have window object. A lot of programmers need it, and now they must use node-fetch package/library for this. I think, server should have possibility to communicate with other servers/APIs, and without package we would need a lot of code to do so, why not add `fetch()` to node.js ?

**Comment by zenflow** [comment]
> The key reason fetch() is not happening in nodejs is that it is a gargantuan amount of work that no company is willing to sponsor.
> 
> node-fetch does 80% of what’s needed and it is extremely easy to install.

@mcollina https://twitter.com/matteocollina/status/1360623954231234564
