### ISSUE TITLE
Who are Node.js' constituencies

### ISSUE THREAD

**Issue by mmarchini** [nodejs/next-10#6]
Context from discussion:

Having a clear idea of who are our constituencies (could also be called stakeholders?) can help us prioritize decisions and/or which features/changes should be included in the project. Inspired on the [HTTP spec](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies).

Constituencies brainstorm:

* Direct end users
  * Users who run tools themselves (install Node, run tool, deal with errors)
* Application operators  
* Application Developers
  * front-end tool consumers
  * back-end server authors
  * hobby developers
  * professional developers
  * tool authors
* library/package authors
* Node.js core maintainers

The list above is not prioritized or exhaustive and we should continue discussion on this topic.

**Comment by mhdawson** [comment]
@mmarchini I think the action was to create a PR to add these to the repo as opposed to an issue (although I might have written that wrong in the minutes).

I think we want it landed in the repo as something we can reference in future work.

**Comment by mmarchini** [comment]
I thought it was an issue, since the list is still under discussion. I might be wrong though

**Comment by mhdawson** [comment]
I figure we can refine the list in the PR.

**Comment by mmarchini** [comment]
I'll open a PR then :)

**Comment by mmarchini** [comment]
Superseded by #7
