### ISSUE TITLE
Define a Security Model

### ISSUE THREAD

**Issue by bmeck** [nodejs/next-10#60]
We have some old documents on Node's set of security goals and guarantees. They are several years old and were not merged into repositories on Node core.

In order to properly deal w/ constituencies that are impacting security invariants of Node, we need to define the actual security guarantees, scope, and concerns of the core runtime.

Likely this would be looking at internals and user code separately and what we wish to enable for both. E.G. If we recommend users do something, why would core not follow the same recommendation by default.

**Comment by mcollina** [comment]
I agree. This would also help when triaging vulnerabilities.
