### ISSUE TITLE
Find better meeting time

### ISSUE THREAD

**Issue by mhdawson** [nodejs/next-10#63]
The current does not seem to be working for people.

@nodejs/next-10 please fill in this doodle poll - https://doodle.com/poll/fpyew5mn6ip9ascb?utm_source=poll&utm_medium=link

**Comment by mcollina** [comment]
I think the link is wrong.

**Comment by mhdawson** [comment]
@mcollina thanks for catching that, correct link - https://doodle.com/poll/fpyew5mn6ip9ascb?utm_source=poll&utm_medium=link

**Comment by mhdawson** [comment]
@BethGriggs, @bmeck, @darcyclarke, @sheplu, @bnb, @ruyadorno, @joesepi. @wesleytodd, @mmarchini  Could you fill out the doodle ?

**Comment by mhdawson** [comment]
From the Doodle Mondays at 11 ET seems to be the best time. That still does not cover everybody though so I'll explore if we can find a second time to alternate with that will work.

I moved the next meeting to next monday.  We should have lots to cover. 

* We have the survey results which I'll add to the repo
* We have collaborator feedback on the technical brainstorm in the fun retro as well!

**Comment by mhdawson** [comment]
@BethGriggs, @bmeck, @darcyclarke, @sheplu, @bnb, @ruyadorno, @joesepi. @wesleytodd, @mmarchini  FYI ^^

**Comment by sheplu** [comment]
From what I see on the doodle the second best slot seems to be Wednesday ( 3 or 4 pm CET). I think we were using this slot before moving to the current one due to lack of people. Should we try it again or find a better spot ?

**Comment by mhdawson** [comment]
Unfortunately the second best one did not seen to cover @darcyclarke, who was the only one who could not make the first one :(

**Comment by darcyclarke** [comment]
Don't worry about me @mhdawson, I'll try and rearrange things

**Comment by mhdawson** [comment]
@darcyclarke if you can make the Monday meeting time, then we can probably stick with that 1 time.

**Comment by mhdawson** [comment]
May be the summer starting but thought I should check if we still think the current time works for people as it was only myself and @legendecas  today.

@BethGriggs, @bmeck, @darcyclarke, @sheplu, @bnb, @ruyadorno, @joesepi. @wesleytodd, @mmarchini

**Comment by mhdawson** [comment]
One other thought I had. Would people be interested in a 1/2 day mini-summit?  It would let us get through the survey results, the feedback we have on the technical brainstorm and talk about "next-10 for collaborators"  and then we could go back to the regular meetings to progress from there?

**Comment by BethGriggs** [comment]
I'd be +1 on a 2-3h session if we can find a suitable slot that allows for a greater number of attendees.

**Comment by mhdawson** [comment]
Doodle to find better meeting time https://doodle.com/poll/a46canyfppq9mcht?utm_source=poll&utm_medium=link

@nodejs/next-10

**Comment by mhdawson** [comment]
Based on the input in the doodle so far I've moved the meetin for now to Wednesday 10-11 ET with the next one being Oct 13. @bmeck @mcollina @sheplu @rxmarbles @joesepi @bnb @GrooveCS @legendecas @BethGriggs

**Comment by mhdawson** [comment]
Closing as we moved the meeting
